[tool.black]
line-length = 99
skip_glob = ["salmon-rnaseq/*", "sc-atac-seq-pipeline/*"]

[tool.isort]
profile = "black"
multi_line_output = 3
src_paths = ["bin"]
skip_glob = ["salmon-rnaseq/*", "sc-atac-seq-pipeline/*"]
